version: '3.8'

services:
  kan-bank-gntda:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3005:3005"  # Expose the app on port 3000
    env_file:
      - .env  # Load environment variables from the .env file